version: "3.9"

services:

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"


  user-service:
    build: ./userService
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  task-service:
    build: ./taskService
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongo_data: